---

# Host-specific values go in host_vars:
# ---
# mysql_bind_ip_address: "192.168.0.100"
# mysql_app_hosts:
#  - "192.168.0.101"
# public_ip_address: "100.100.100.100"
# public_ip_netmask: "255.255.255.0"
# public_ip_gateway: "100.100.100.1"
# private_ip_address: "192.168.0.100"
# private_ip_netmask: "255.255.128.0"


# Sensitive configuration values go in ansible_hosts file:
# ---
# [commons:vars]
# dns_aws_zone_id=zone-id
# mysql_root_password=password
# mysql_app_database=database-name
# mysql_app_user=database-user
# mysql_app_password=password
# mysql_s3_restore_file=s3://s3-bucket/path/to/backup.file
# s3_backup_bucket=bucket-name
# s3_backup_project=project-name
# ssl_certs_directory=/path/to/ssl/certs
# wordpress_akismet_key=akismet-key
# wordpress_s3_restore_file=s3://s3-bucket/path/to/backup.file


wordpress_git_repository: "git@github.com:mlaa/commons.git"
wordpress_hostname: "commons.mla.org"

wordpress_repositories:
  - "plugins/bp-group-documents"
  - "plugins/mla-admin-bar"
  - "plugins/cbox-auth"
  - "themes/cbox-mla"
  - "themes/cbox-mla-blog"
  - "themes/commentpress-mla"
  - "themes/commentpress-mla-groups"
