---

# Sensitive variables. Edit and keep outside version control.

dns_aws_zone_id: "zone-id"

mysql_root_password: "password"
mysql_app_database: "database-name"
mysql_app_user: "database-user"
mysql_app_password: "password"
mysql_s3_restore_file: "s3://s3-bucket/path/to/backup.file"

s3_backup_bucket: "s3-bucket"
s3_backup_project: "project-name"

wordpress_akismet_key: "akismet-key"
wordpress_s3_restore_file: "s3://s3-bucket/path/to/backup.file"
