---

# This application requires Nginx >1.6 (for SPDY support), which is usually not
# available in stable repos. Write your own task if you are not using Debian 7.

- include: "distro/debian7.yml"
  when: "ansible_distribution_release == 'wheezy'"

- name: "Nginx | nginx.conf"
  template:
    src="nginx.conf.j2"
    dest="/etc/nginx/nginx.conf"
  notify: "restart nginx"
  tags: "nginx"

- name: "Nginx | create site directories"
  file:
    path="/etc/nginx/{{ item }}"
    owner="root"
    group="root"
    mode="0755"
    state="directory"
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "conf.d"
    - "include"
  notify: "restart nginx"
  tags: "nginx"

- name: "Nginx | server includes"
  template:
    src="include-{{ item }}.j2"
    dest="/etc/nginx/include/{{ item }}"
  with_items:
    - "php-fpm"
    - "ssl"
    - "wordpress"
  tags:
    - "nginx"

- name: "Nginx | remove default virtual host"
  file:
    path="/etc/nginx/sites-enabled/default"
    state="absent"
  notify: "restart nginx"
  tags: "nginx"

- include: "ufw.yml"
