---

- name: "PHP-FPM | install"
  apt:
    name="{{ item }}"
    state="present"
  with_items:
    - "php5-fpm"
    - "php5-cgi"
    - "php5-cli"
    - "php5-curl"
    - "php5-gd"
    - "php5-json"
    - "php5-mysql"
    - "php-apc"
  tags:
    - "php-fpm"
    - "packages"

- name: "PHP-FPM | raise file upload limit"
  lineinfile:
    dest="/etc/php5/fpm/php.ini"
    regexp="^post_max_size"
    line="post_max_size = {{ php_post_max_size | default('8M') }}"
    state="present"
  notify: "restart php-fpm"
  tags: "php-fpm"

- name: "PHP-FPM | allow wp-cli"
  lineinfile:
    dest="/etc/php5/cli/php.ini"
    regexp="^suhosin.executor.include.whitelist"
    line="suhosin.executor.include.whitelist=\"phar\""
    state="present"
  tags: "php-fpm"

- name: "PHP-FPM | find PHP conf.d"
  stat:
    path="/etc/php5/mods-available"
  register: "php_mods_dir"
  tags: "php-fpm"

- name: "PHP-FPM | apc.ini"
  template:
    src="apc.ini.j2"
    dest="/etc/php5/mods-available/apc.ini"
  notify: "restart php-fpm"
  when: "php_mods_dir.stat.exists"
  tags: "php-fpm"

- name: "PHP-FPM | apc.ini"
  template:
    src="apc.ini.j2"
    dest="/etc/php5/fpm/conf.d/apc.ini"
  notify: "restart php-fpm"
  when: "php_mods_dir.stat.exists == false"
  tags: "php-fpm"

- name: "PHP-FPM | php-fpm.conf"
  template:
    src="php-fpm.conf.j2"
    dest="/etc/php5/fpm/php-fpm.conf"
  notify: "restart php-fpm"
  tags: "php-fpm"

- name: "PHP-FPM | pool.conf"
  template:
    src="www.conf.j2"
    dest="/etc/php5/fpm/pool.d/www.conf"
  notify: "restart php-fpm"
  tags: "php-fpm"
