---

- name: "Backup | mysql install backup script"
  template:
    src="backup-db-to-s3.sh.j2"
    dest="{{ admin_home_directory }}/bin/backup-mysql.sh"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0744"
  when: s3_backup_bucket is defined and mysql_app_database is defined
  tags:
    - "s3-backup"
    - "mysql"

- name: "Backup | mysql backup script cron job"
  sudo: "no"
  cron:
    name="mysql backup"
    special_time="hourly"
    job="~/bin/backup-mysql.sh >> ~/log/backup-mysql.log"
  when: s3_backup_bucket is defined and mysql_app_database is defined
  tags:
    - "s3-backup"
    - "mysql"
