---

- name: "Self-signed SSL | create CA certificate directory"
  file:
    path="/usr/share/ca-certificates/app"
    state="directory"
    owner="root"
    group="root"
    mode="0755"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | copy OpenSSL config template"
  copy:
    src="self-signed-certificate-openssl.cnf.example"
    dest="/etc/ssl/self-signed-certificate-openssl.cnf.example"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | init script"
  copy:
    src="self-signed-certificate.sh"
    dest="/etc/init.d/self-signed-certificate"
    mode="0755"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | register init script"
  shell:
    update-rc.d self-signed-certificate defaults 95
  tags:
    - "ssl"
    - "self-signed"
