---

- name: "WordPress | install wp-cli"
  sudo: "no"
  get_url:
    url="{{ wordpress_cli }}"
    dest="{{ admin_home_directory }}/bin/wp-cli.phar"
  tags: "wordpress"

- name: "WordPress | install SASS"
  gem:
    name="sass"
    state="latest"
  tags: "wordpress"

- name: "WordPress | useful exports in bash"
  template:
    src="local_exports.j2"
    dest="{{ admin_home_directory }}/.local_exports"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0644"
  tags: "wordpress"

- include: "config.yml"
- include: "nginx.yml"
