---

- name: "WordPress | download latest version"
  sudo: "no"
  get_url:
    url="{{ wordpress_latest_version }}"
    dest="{{ admin_home_directory }}/pkg/wordpress.latest.tar.gz"
  tags: "wordpress"

- include: "git.yml"

- name: "WordPress | create webroot directory"
  file:
    path="{{ wordpress_install_directory }}/public"
    state="directory"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0755"
  tags: "wordpress"

- name: "WordPress | extract archive"
  sudo: "no"
  shell:
    creates="{{ wordpress_install_directory }}/public/index.php"
    tar -xzf {{ admin_home_directory }}/pkg/wordpress.latest.tar.gz --strip-components 1 -C {{ wordpress_install_directory }}/public
  tags: "wordpress"

- name: "WordPress | install wp-cli"
  sudo: "no"
  get_url:
    url="{{ wordpress_cli }}"
    dest="{{ admin_home_directory }}/bin/wp-cli.phar"
  tags: "wordpress"

- name: "WordPress | install SASS"
  gem:
    name="sass"
    state="latest"
  tags: "wordpress"

- include: "config.yml"
- include: "nginx.yml"
