---

- name: "WordPress Install | change webroot permissions"
  file:
    path="{{ www_root }}"
    owner="{{ ansible_ssh_user }}"
    group="{{ ansible_ssh_user }}"
    state="directory"
    recurse="yes"
  tags:
    - "wordpress-install"

- name: "WordPress Install | restore logs permissions"
  file:
    path="{{ www_root }}/{{ item.key }}/logs"
    owner="{{ web_user }}"
    group="{{ web_group }}"
    mode="0755"
    state="directory"
  with_dict: "wordpress_sites"
  tags:
    - "wordpress-install"

- name: "WordPress Install | create conf directory"
  file:
    path="{{ www_root }}/{{ item.key }}/conf"
    owner="{{ ansible_ssh_user }}"
    group="{{ ansible_ssh_user }}"
    state="directory"
  with_dict: "wordpress_sites"
  tags:
    - "wordpress-install"

- name: "WordPress Install | create .env template"
  template:
    src="env.j2"
    dest="{{ www_root }}/{{ item.key }}/conf/env.template"
    owner="{{ ansible_ssh_user }}"
    group="{{ ansible_ssh_user }}"
  with_dict: "wordpress_sites"
  tags:
    - "wordpress-install"

- include: "mysql.yml"
- include: "nginx.yml"
- include: "scripts.yml"
