---

- name: "WordPress Install | increase mysql open files limit"
  lineinfile:
    dest="/etc/mysql/my.cnf"
    state="present"
    regexp="^open_files_limit"
    line="open_files_limit = 32768"
    insertafter="^\[mysqld\]"
  tags:
    - "wordpress-install"
    - "mysql"

- name: "WordPress Install | increase system open files hard limit"
  lineinfile:
    dest="/etc/security/limits.conf"
    state="present"
    regexp="^mysql"
    line="mysql hard nofile 32768"
  tags:
    - "wordpress-install"
    - "mysql"

- name: "WordPress Install | mysql credentials file"
  template:
    src="user.my.cnf.j2"
    dest="~/.my.cnf"
    owner="{{ ansible_ssh_user }}"
    group="{{ ansible_ssh_user }}"
    mode="0600"
  tags:
    - "wordpress-install"
    - "mysql"
