---

- name: "WordPress Install | install commons site includes"
  template:
    src="nginx-include-{{ item }}.j2"
    dest="/etc/nginx/includes.d/commons/{{ item }}"
  with_items:
    - "fedora.conf"
    - "rewrites.conf"
  tags:
    - "wordpress-install"
    - "nginx"
