---

- name: "WordPress Install | create bin directory"
  sudo: "no"
  file:
    dest="{{ www_root }}/{{ item.key }}/bin"
    state="directory"
  with_dict: "wordpress_sites"
  tags:
    - "wordpress-install"

- name: "WordPress Install | commons install script"
  sudo: "no"
  template:
    src="install-commons.sh.j2"
    dest="{{ www_root }}/commons/bin/install-commons.sh"
    mode="0744"
  when: "wordpress_sites.commons is defined"
  tags:
    - "wordpress-install"

- name: "WordPress Install | vanilla install script"
  sudo: "no"
  template:
    src="install-vanilla.sh.j2"
    dest="{{ www_root }}/{{ item.key }}/bin/install-vanilla.sh"
    mode="0744"
  with_dict: "wordpress_sites"
  tags:
    - "wordpress-install"
