---

- name: "DNS | Create config directory"
  file:
    path="/etc/aws-route53"
    state="directory"
  when: route53_zone_id is defined
  tags: "route53-dns"

- name: "DNS | create changeset template"
  template:
    src="{{ item }}.j2"
    dest="/etc/aws-route53/{{ item }}"
  with_items:
    - "changeset.json.sample"
    - "zone-id"
  when: route53_zone_id is defined
  tags: "route53-dns"

- name: "DNS | init script"
  copy:
    src="aws-route53.sh"
    dest="/etc/init.d/aws-route53"
    mode="0755"
  when: route53_zone_id is defined
  tags: "route53-dns"

- name: "DNS | register init script"
  shell:
    update-rc.d aws-route53 defaults
  when: route53_zone_id is defined
  tags: "route53-dns"

- name: "DNS | create DNS records"
  shell:
    /etc/init.d/aws-route53 start
  when: route53_zone_id is defined
  tags: "route53-dns"
