---

- name: "DNS | get public ip address"
  shell: curl ipv4.icanhazip.com
  register: "public_ip_address"
  when: route53_zone_id is defined
  tags: "route53-dns"

- name: "DNS | create DNS records changeset"
  template:
    src="aws-route53.json.j2"
    dest="{{ admin_home_directory }}/tmp/aws-route53.json"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0644"
  when: route53_zone_id is defined
  tags: "route53-dns"

- name: "DNS | create DNS records"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/aws-route53.created"
    aws route53 change-resource-record-sets --hosted-zone-id {{ route53_zone_id }} --change-batch file://{{ admin_home_directory }}/tmp/aws-route53.json && touch {{ admin_home_directory }}/tmp/aws-route53.created
  when: route53_zone_id is defined
  tags: "route53-dns"
