---

wordpress_sites:
  commons:
    repo_branch: "master"
    ssl:
      enabled: true
      cert: "~/.ssh/deploy/commons/ssl/commons.mla.org.crt"
      key: "~/.ssh/deploy/commons/ssl/commons.mla.org.key"
    system_cron: true
    env:
      wp_env: "production"
