---

- name: "MySQL | install"
  apt:
    pkg="{{ item }}"
    state="present"
  with_items:
    - "mysql-server"
    - "python-mysqldb"
  notify: enable mysql
  tags:
    - "mysql"
    - "packages"

- name: "MySQL | my.cnf"
  template:
    src="my.cnf.j2"
    dest="/etc/mysql/my.cnf"
  notify: restart mysql
  tags: "mysql"

- name: "MySQL | set root password"
  sudo: "no"
  mysql_user:
    name="root"
    password="{{ mysql_root_password | default('password') }}"
    host="{{ item }}"
    state="present"
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost"
  tags: "mysql"

- name: "MySQL | credentials file"
  template:
    src="user.my.cnf.j2"
    dest="{{ admin_home_directory }}/.my.cnf"
    owner="{{ admin_user }}"
    mode="0600"
  tags: "mysql"

- name: "MySQL | create app database"
  sudo: "no"
  mysql_db:
    name="{{ mysql_app_database }}"
    state="present"
  when: mysql_app_database is defined
  tags: "mysql"

- name: "MySQL | create app account"
  sudo: "no"
  mysql_user:
    name="{{ mysql_app_user | default('root') }}"
    password="{{ mysql_app_password | default('password') }}"
    host="{{ item }}"
    priv="{{ mysql_app_database }}.*:ALL"
    state="present"
  with_items: "{{ mysql_default_hosts + (mysql_app_hosts | default([])) }}"
  when: mysql_app_database is defined
  tags: "mysql"

- name: "MySQL | install mysqltuner"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/bin/mysqltuner.pl"
    curl -L {{ mysql_tuner }} > {{ admin_home_directory }}/bin/mysqltuner.pl
  tags: "mysql"

- include: "ufw.yml"
