---

- name: "WordPress | migrate URLs"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/mysql.backup.migrated"
    php {{ admin_home_directory }}/bin/wp-cli.phar search-replace --skip-columns=guid --network --url='{{ wordpress_production_hostname }}' --path='{{ wordpress_install_directory }}/public' '{{ wordpress_production_hostname }}' '{{ wordpress_hostname }}' && touch {{ admin_home_directory }}/tmp/mysql.backup.migrated
  when: wordpress_production_hostname is defined
  tags:
    - "s3-import"
    - "wordpress"
    - "mysql"
    - "migrate"

- name: "WordPress | update WordPress site URL"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/wordpress.siteurl.updated"
    php {{ admin_home_directory }}/bin/wp-cli.phar option update siteurl 'https://{{ wordpress_hostname }}' --path='{{ wordpress_install_directory }}/public' && touch {{ admin_home_directory }}/tmp/wordpress.config.siteurl.updated
  when: wordpress_production_hostname is defined
  tags:
    - "s3-import"
    - "wordpress"
    - "mysql"
    - "migrate"

- name: "WordPress | update WordPress home URL"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/wordpress.home.updated"
    php {{ admin_home_directory }}/bin/wp-cli.phar option update home 'https://{{ wordpress_hostname }}' --path='{{ wordpress_install_directory }}/public' && touch {{ admin_home_directory }}/tmp/wordpress.config.home.updated
  when: wordpress_production_hostname is defined
  tags:
    - "s3-import"
    - "wordpress"
    - "mysql"
    - "migrate"
