---

- name: "MySQL | fetch latest daily backup from s3"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/mysql.backup.sql.gz"
    aws s3 cp {{ mysql_s3_restore_file }} {{ admin_home_directory }}/tmp/mysql.backup.sql.gz
  when: mysql_app_database is defined
  tags:
    - "s3-import"
    - "mysql"

- name: "MySQL | import latest backup"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/mysql.backup.imported"
    gunzip -c {{ admin_home_directory }}/tmp/mysql.backup.sql.gz | mysql {{ mysql_app_database }} && touch {{ admin_home_directory }}/tmp/mysql.backup.imported
  when: mysql_app_database is defined
  tags:
    - "s3-import"
    - "mysql"
