---

- name: "WordPress | nginx server includes"
  template:
    src="include-{{ item }}.j2"
    dest="/etc/nginx/include/{{ item }}"
  with_items:
    - "php-fpm"
    - "ssl"
  tags:
    - "wordpress"
    - "nginx"

- name: "WordPress | nginx virtual hosts"
  template:
    src="nginx-{{ item }}.j2"
    dest="/etc/nginx/sites-available/{{ item }}"
  with_items:
    - "wordpress"
    - "wordpress-ssl"
  tags:
    - "wordpress"
    - "nginx"

- name: "WordPress | nginx virtual host symlinks"
  file:
    src="/etc/nginx/sites-available/{{ item }}"
    dest="/etc/nginx/sites-enabled/{{ item }}"
    state="link"
  with_items:
    - "wordpress"
    - "wordpress-ssl"
  notify: reload nginx
  tags:
    - "wordpress"
    - "nginx"
