---

- name: "WordPress | fetch latest daily backup from s3"
  sudo: "no"
  shell:
    creates="{{ admin_home_directory }}/tmp/wordpress.backup.tar.gz"
    aws s3 cp {{ wordpress_s3_restore_file }} {{ admin_home_directory }}/tmp/wordpress.backup.tar.gz
  tags:
    - "s3-import"
    - "wordpress"

- name: "WordPress | create app directory"
  file:
    path="{{ wordpress_install_directory }}"
    state="directory"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0755"
  tags:
    - "s3-import"
    - "wordpress"

- name: "WordPress | extract latest backup"
  sudo: "no"
  shell:
    creates="{{ wordpress_install_directory }}/wp-config.php.j2"
    tar -xzf {{ admin_home_directory }}/tmp/wordpress.backup.tar.gz -C {{ wordpress_install_directory }}
  tags:
    - "s3-import"
    - "wordpress"

- name: "WordPress | change directory permissions"
  file:
    path="{{ wordpress_install_directory }}/public/wp-content/{{ item }}"
    owner="www-data"
    group="www-data"
    recurse="yes"
    state="directory"
  with_items:
    - "blogs.dir"
    - "uploads"
    - "wptouch-data"
  tags:
    - "s3-import"
    - "wordpress"
    - "permissions"

- include: "config.yml"
- include: "nginx.yml"
