---

- name: "SSL | generate stronger DHE parameter"
  shell:
    creates="/etc/ssl/certs/dhparam.pem"
    openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  tags:
    - "ssl"

- name: "SSL | create certificate directory"
  file:
    path="/etc/ssl/private/app"
    state="directory"
    owner="root"
    group="root"
    mode="0700"
  tags:
    - "ssl"

- name: "SSL | install official certificates"
  copy:
    src="{{ item }}"
    dest="/etc/ssl/private/app"
    owner="root"
    group="root"
    mode="0600"
  with_fileglob: "{{ ssl_certs_directory }}/*"
  tags:
    - "ssl"
