---

- name: "Fail2Ban | install"
  apt:
    name="fail2ban"
    state="present"
  notify: "enable fail2ban"
  tags:
    - "fail2ban"
    - "packages"

- name: "Fail2Ban | UFW action"
  copy:
    src="ufw.conf"
    dest="/etc/fail2ban/action.d/ufw.conf"
  tags:
    - "fail2ban"

- name: "Fail2Ban | WordPress login filter"
  copy:
    src="wordpress.conf"
    dest="/etc/fail2ban/filter.d/wordpress.conf"
  tags:
    - "fail2ban"

- name: "Fail2Ban | jail.local"
  template:
    src="jail.local.j2"
    dest="/etc/fail2ban/jail.local"
  notify: "restart fail2ban"
  tags:
    - "fail2ban"
