---

- name: "Self-signed SSL | create certificate directory"
  file:
    path="/etc/ssl/private/app"
    state="directory"
    owner="root"
    group="root"
    mode="0700"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | create CA certificate directory"
  file:
    path="/usr/share/ca-certificates/app"
    state="directory"
    owner="root"
    group="root"
    mode="0755"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | copy OpenSSL config for self-signed certificate"
  template:
    src="self-signed-certificate-openssl.cnf.j2"
    dest="/etc/ssl/self-signed-certificate-openssl.cnf"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | create self-signed wildcard browser certificate"
  shell:
    creates="/etc/ssl/private/app/server.crt"
    openssl req -new -nodes -x509 -batch -days 3650 -newkey rsa:2048 -keyout /etc/ssl/private/app/server.key -out /etc/ssl/private/app/server.crt -extensions v3_req -config /etc/ssl/self-signed-certificate-openssl.cnf
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | create self-signed CA certificate"
  shell:
    creates="/usr/share/ca-certificates/app/server.crt"
    openssl req -new -nodes -x509 -batch -days 3650 -key /etc/ssl/private/app/server.key -out /usr/share/ca-certificates/app/server.crt -extensions v3_ca -config /etc/ssl/self-signed-certificate-openssl.cnf
  notify: "update ca-certificates"
  tags:
    - "ssl"
    - "self-signed"

- name: "Self-signed SSL | add self-signed CA certificate"
  lineinfile:
    dest="/etc/ca-certificates.conf"
    regexp="^app/server.crt$"
    line="app/server.crt"
    state="present"
  notify: "update ca-certificates"
  tags:
    - "ssl"
    - "self-signed"
