---

- name: "AWS | create .aws directory"
  file:
    path="{{ admin_home_directory }}/.aws"
    state="directory"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0700"
  when: aws_credentials_file is defined
  tags:
    - "common"
    - "aws"

- name: "AWS | copy credentials"
  copy:
    src="{{ aws_credentials_file }}"
    dest="{{ admin_home_directory }}/.aws/config"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    mode="0600"
  when: aws_credentials_file is defined
  tags:
    - "common"
    - "aws"
