---

- name: "SSH | set SSH port"
  lineinfile:
    dest="/etc/ssh/sshd_config"
    regexp="^Port "
    line="Port {{ ssh_port }}"
    state="present"
  notify: "restart ssh"
  tags: "ssh"

- name: "SSH | disable root"
  lineinfile:
    dest="/etc/ssh/sshd_config"
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state="present"
  notify: "restart ssh"
  tags:
    - "common"
    - "ssh"

- name: "SSH | disable password authentication"
  lineinfile:
    dest="/etc/ssh/sshd_config"
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state="present"
  notify: "restart ssh"
  tags:
    - "common"
    - "ssh"

- name: "SSH | disable PAM"
  lineinfile:
    dest="/etc/ssh/sshd_config"
    regexp="^UsePAM"
    line="UsePAM no"
    state="present"
  notify: "restart ssh"
  tags:
    - "common"
    - "ssh"

- name: "SSH | public key authentication"
  lineinfile:
    dest="/etc/ssh/sshd_config"
    regexp="^AuthorizedKeysFile"
    line="AuthorizedKeysFile %h/.ssh/authorized_keys"
    state="present"
  notify: "restart ssh"
  tags:
    - "common"
    - "ssh"

- name: "SSH | allow sshusers"
  lineinfile:
    dest="/etc/ssh/sshd_config"
    regexp="^AllowGroups"
    line="AllowGroups sshusers"
    state="present"
  notify: "restart ssh"
  tags:
    - "common"
    - "ssh"
