---

- include: "packages.yml"
- include: "networking.yml"
- include: "timezone.yml"
- include: "known-hosts.yml"

# Local VM tasks
- include: "dnsmasq.yml"

# Amazon EC2 tasks
- include: "aws-ec2-user-data.yml"
- include: "aws-route53.yml"
